"""Start-Here info body with inline styles (survives Anki deck-description sanitization)."""
import re

_BOX = ('max-width:640px;margin:0 auto;padding:12px;text-align:left;'
        'line-height:1.4;font-size:16px;font-family:"Noto Sans CJK JP","Hiragino Sans",sans-serif')
_COVER = ('display:block;max-width:200px;width:100%;margin:0 auto 8px;'
          'border-radius:6px;box-shadow:0 3px 10px rgba(0,0,0,0.25)')
_H1 = 'font-size:26px;margin:4px 0 2px;text-align:center;font-weight:700;line-height:1.15'
_SUB = 'text-align:center;opacity:0.7;margin:0 0 10px;font-style:italic;font-size:14px'
_H2 = 'font-size:17px;margin:14px 0 4px;border-bottom:1px solid currentColor;padding-bottom:2px;font-weight:600;opacity:0.95'
_P = 'margin:4px 0'
_UL = 'padding-left:20px;margin:4px 0'
_LI = 'margin:2px 0'
_CODE = 'background:rgba(128,128,128,0.22);padding:0 5px;border-radius:3px;font-size:14px;font-family:monospace'
_A = 'color:#4a9eff;text-decoration:none'
_TIP = 'background:rgba(255,200,80,0.15);border-left:3px solid #ffc850;padding:6px 10px;border-radius:5px;margin:8px 0;font-size:15px'
_AUTHOR = 'text-align:center;margin:14px 0 4px;padding:10px;border:1px solid rgba(128,128,128,0.4);border-radius:8px'
_NAME = 'font-size:18px;font-weight:600;margin-bottom:3px'


def build() -> str:
    body = f"""<div style="{_BOX}">
<img style="{_COVER}" src="cover.png">
<h1 style="{_H1}">Minna no Nihongo I + II</h1>
<div style="{_SUB}">N5 + N4 vocabulary deck · 50 lessons · 2,156 words</div>

<h2 style="{_H2}">What this deck is</h2>
<p style="{_P}">Every vocabulary word from all 50 lessons of <em>Minna no Nihongo Shokyu I &amp; II</em> (Second Edition) — the standard introductory Japanese textbook used worldwide. Each word is presented as kanji + furigana with pitch-accent coloring, native Japanese audio, an example sentence (with audio), a kanji stroke-order animation, and a memorable English mnemonic.</p>

<h2 style="{_H2}">Deck structure</h2>
<ul style="{_UL}">
<li style="{_LI}"><code style="{_CODE}">Lesson 01</code> … <code style="{_CODE}">Lesson 50</code> — vocabulary sub-decks, study in order</li>
<li style="{_LI}"><code style="{_CODE}">Quiz::Lesson NN</code> — 4-option multiple-choice review for each lesson (JP↔EN)</li>
</ul>

<h2 style="{_H2}">How to study</h2>
<ul style="{_UL}">
<li style="{_LI}"><b>1 lesson per week</b> if you study with the textbook; the deck mirrors textbook order.</li>
<li style="{_LI}"><b>Self-paced:</b> unlock one lesson at a time. After 2–3 days of review, suspend it and move to the next.</li>
<li style="{_LI}">Each word generates up to <b>5 cards</b>: JP→EN, EN→JP, Audio→JP+EN, sentence cloze, kanji stroke order. Suspend templates you don't want in deck options.</li>
<li style="{_LI}">Quiz sub-decks are optional reinforcement — open them after finishing a lesson's vocab.</li>
</ul>

<h2 style="{_H2}">Reading the card</h2>
<ul style="{_UL}">
<li style="{_LI}"><b>Pitch accent:</b> red bar over high mora, red drop bar marks the pitch fall (Tokyo dialect).</li>
<li style="{_LI}"><b>Mnemonic:</b> the 🧠 box links the kana sound to an English association — read it once when you first see the word.</li>
<li style="{_LI}"><b>Kanji animation:</b> SVG strokes draw in correct order — watch it once to learn the path.</li>
<li style="{_LI}"><b>Mascot &amp; progress bar:</b> at the bottom of every card. Mascot evolves every 10 lessons.</li>
</ul>

<div style="{_TIP}">💡 <b>Tip:</b> turn on FSRS via the ⚙ cog next to a deck → Options → FSRS, for much better scheduling than the default SM-2 algorithm.</div>

<h2 style="{_H2}">Data sources</h2>
<ul style="{_UL}">
<li style="{_LI}">Vocab list — <a style="{_A}" href="https://learnjapaneseaz.com">learnjapaneseaz.com</a></li>
<li style="{_LI}">Pitch accent — <a style="{_A}" href="https://github.com/mifunetoshiro/kanjium">kanjium</a> (CC0)</li>
<li style="{_LI}">Kanji strokes — <a style="{_A}" href="https://kanjivg.tagaini.net">KanjiVG</a> (CC BY-SA 3.0)</li>
<li style="{_LI}">Example sentences — <a style="{_A}" href="https://tatoeba.org">Tatoeba</a> (CC-BY 2.0 FR)</li>
<li style="{_LI}">Audio — Microsoft edge-tts (ja-JP-NanamiNeural)</li>
<li style="{_LI}">Mnemonics — generated by <a style="{_A}" href="https://ollama.com">Ollama</a> running gemma4:e4b locally</li>
</ul>

<div style="{_AUTHOR}">
  <div style="{_NAME}">Pavel</div>
  <div><a style="{_A}" href="https://iampavel.dev">iampavel.dev</a></div>
  <div><a style="{_A}" href="mailto:contact@iampavel.dev">contact@iampavel.dev</a></div>
</div>
</div>
"""
    return re.sub(r"\s*\n\s*", "", body)
